/* CAT Prep Question Bank — home page guide. Chapter data lives in data/cat20XX.js */
window.CAT_DATA = window.CAT_DATA || [];
window.CAT_README = [
"# 🎯 CAT — Common Admission Test",
"",
"> India's premier MBA entrance exam, conducted by the IIMs. This site gives you **year-wise practice built around the last 10 CAT papers (2016–2025)** — every section of every year, with instant answers and fully worked solutions.",
"",
"## How this bank is built",
"",
"Each year has three sections, exactly like the real exam:",
"",
"| Section | What it tests | Typical share |",
"|---|---|---|",
"| **VARC** — Verbal Ability & Reading Comprehension | RC passages, para-jumbles, para-summary, odd-sentence-out | ~24 questions |",
"| **DILR** — Data Interpretation & Logical Reasoning | Puzzle sets, arrangements, tables/charts, games & tournaments | ~20–22 questions |",
"| **QA** — Quantitative Ability | Arithmetic, algebra, geometry, number system, modern maths | ~22 questions |",
"",
"For every year from **2016 to 2025** you get a question set per section that mirrors that year's **actual paper**: the same topic mix, question types, difficulty curve and famous 'trap' patterns — plus a **Paper insights** tab that tells you how that year really played out (pattern, difficulty, what a good attempt looked like).",
"",
"⚠️ **Note:** the questions here are original re-creations modeled on the publicly known pattern and topics of each year's paper — they are practice equivalents, not the official question papers. For the official released papers, use the IIM CAT candidate portal.",
"",
"## Marking scheme (mirrored here)",
"",
"- **+3** for every correct answer",
"- **−1** for a wrong MCQ",
"- **No negative marking** for TITA (Type-In-The-Answer) questions — here they are shown as MCQs but tagged **⌨️ TITA**, and the score bar applies no penalty when you miss them",
"",
"## How the CAT has changed, 2016 → 2025",
"",
"| Era | Duration | Questions | Notes |",
"|---|---|---|---|",
"| 2016–2019 | 180 min (60/section) | 100 (34 VARC · 32 DILR · 34 QA) | Longer, stamina-heavy papers |",
"| 2020 | 120 min (40/section) | 76 | COVID year — 3 slots, shorter paper |",
"| 2021–2023 | 120 min (40/section) | 66 (24 · 20 · 22) | The modern short format |",
"| 2024–2025 | 120 min (40/section) | 68 (24 · 22 · 22) | DILR expanded to 22 |",
"",
"## How to use this site",
"",
"1. **Start with the two most recent years** (2025, 2024) to calibrate against the current format.",
"2. Use the **difficulty filter chips** (🟢🟡🔴) inside each section to warm up before attempting the hard tier.",
"3. Read every solution — even for questions you got right. The **why the other options are wrong** part is where CAT accuracy is built.",
"4. Check the **Paper insights** tab for each section: it tells you what the real paper looked like and what score was competitive.",
"5. Track progress with **Mark as done** — the sidebar shows ✓ per section and the bar tracks your overall coverage.",
"",
"---",
"*Independent practice material. Not affiliated with or endorsed by the IIMs. CAT is conducted by the Indian Institutes of Management.*"
].join("\n");
