/* Study tools content: QA formula sheet + strategy playbook (original reference material) */
window.CAT_TOOLS = {
formulas: [
"# 📐 QA Formula Sheet",
"",
"> Every formula that has appeared repeatedly across CAT 2016–2025 QA sections, grouped by topic. Skim before every practice session — recall speed is half the battle. (Bookmark hard questions with ⭐ and revisit with these open.)",
"",
"## Percentages, Profit & Loss",
"",
"| Situation | Formula |",
"|---|---|",
"| Successive changes of a% then b% | Net % = a + b + ab/100 |",
"| Profit % | (SP − CP)/CP × 100 |",
"| Discount then profit | SP = MP × (1 − d/100); profit% on CP |",
"| Markup m%, discount d% | Profit% = m − d − md/100 |",
"| False weight (sells x g as 1000 g) | Gain% = (1000 − x)/x × 100 |",
"",
"## Simple & Compound Interest",
"",
"| Situation | Formula |",
"|---|---|",
"| SI | P·r·t/100 |",
"| CI amount | P(1 + r/100)ᵗ |",
"| CI − SI for 2 years | P(r/100)² |",
"| Doubling under SI at r% | t = 100/r years |",
"",
"## Ratio, Mixtures, Alligation",
"",
"- Alligation: cheaper : dearer = (dearer price − mean) : (mean − cheaper price)",
"- Repeated replacement: final pure amount = V(1 − x/V)ⁿ after n replacements of x from volume V",
"- If a : b = 3 : 5 and both increase by k, the ratio moves **toward 1 : 1**",
"",
"## Averages",
"",
"- Removing one value: removed = old total − new total",
"- Overlap trick: sum(first m) + sum(last m) − grand total = the overlapping middle term(s)",
"- Weighted average sits closer to the group with more members",
"",
"## Time, Speed & Distance",
"",
"| Situation | Formula |",
"|---|---|",
"| Equal distances at u and v | Average speed = 2uv/(u+v) (harmonic mean) |",
"| Train past a pole | time = L/v |",
"| Train past platform of length P | time = (L+P)/v |",
"| Upstream / downstream | u = b − s, d = b + s ⇒ b = (u+d)/2, s = (d−u)/2 |",
"| Relative speed | Same direction: v₁−v₂ · Opposite: v₁+v₂ |",
"| Races: A beats B by x m over D | B's distance when A finishes = D − x; chain ratios multiply |",
"",
"## Time & Work",
"",
"- Rates add: 1/a + 1/b = 1/together",
"- Total work = LCM of days (clean unit method)",
"- Pair sums: (a+b)+(b+c)+(c+a) = 2(a+b+c) — halve to get combined rate",
"- Person leaves early: split the timeline into phases and add work done in each",
"",
"## Number System",
"",
"| Tool | How |",
"|---|---|",
"| Units digit of aᵇ | Cycle of the units digit (period 1, 2 or 4) — reduce b mod cycle |",
"| Last two digits of 7ⁿ | Cycle 07, 49, 43, 01 (period 4) |",
"| Remainder of aᵇ mod m | Find the cycle of aᵏ mod m; reduce the exponent mod the period |",
"| Trailing zeros of n! | ⌊n/5⌋ + ⌊n/25⌋ + ⌊n/125⌋ + … (watch the jumps of size 2 at multiples of 25) |",
"| Number of factors of N = pᵃqᵇrᶜ | (a+1)(b+1)(c+1) |",
"| x² − y² = N (positive integers) | Count factor pairs of N with the same parity |",
"| Multiples of k in [A, B] | ⌊B/k⌋ − ⌈A/k⌉ + 1 |",
"",
"## Algebra",
"",
"- x + 1/x = k ⇒ x² + 1/x² = k² − 2; x³ + 1/x³ = k³ − 3k",
"- Quadratic ax² + bx + c: sum = −b/a, product = c/a; (x−p)(x−q) < 0 ⇔ p < x < q",
"- Logs: logₐx + logₐy = logₐ(xy); log_{a^k}x = (1/k)logₐx — always check the **domain** before accepting roots",
"- max(f, g) is minimised where an increasing f crosses a decreasing g",
"- |x−a| + |x−b| ≤ k: constant (= b−a) between a and b; solve the two outer linear cases",
"- AM ≥ GM: for positive reals, minimum of sums of reciprocal-type expressions usually sits at the equality point",
"",
"## Geometry & Mensuration",
"",
"| Object | Facts |",
"|---|---|",
"| Right triangle, legs a, b, hyp c | Inradius r = (a + b − c)/2 · Area = rs (s = semi-perimeter) |",
"| Altitude to hypotenuse | h² = (segments product): h = √(mn) |",
"| Chord of length 2ℓ at distance d | r² = ℓ² + d²; perpendicular from centre bisects the chord |",
"| Two parallel chords | Same side: gap = d₂ − d₁ · Opposite sides: gap = d₁ + d₂ (state which!) |",
"| Similar triangles | Area ratio = (side ratio)² |",
"| Medians & centroid | Centroid splits medians 2:1; triangle area = 3 × area of a centroid sub-triangle |",
"| Cone | Slant l = √(r²+h²); CSA = πrl; TSA = πr(l+r); common triples: 3-4-5, 5-12-13, 7-24-25 |",
"| Cylinder in cone optimisation | Max volume at r_cyl = 2R/3 |",
"| Regular hexagon vs equilateral triangle, equal perimeter | Area ratio = 3 : 2 |",
"",
"## Modern Maths (P&C, Probability, Functions, Progressions)",
"",
"- Committees with 'at least one X': total − none (complement is almost always faster)",
"- Arrangements with a block: glue the block (k! internal orders × (n−k+1)! external)",
"- Onto functions from n-set to 3-set: 3ⁿ − 3·2ⁿ + 3 (inclusion–exclusion)",
"- f(f(x)) iteration: compute one layer at a time, simplify before the next",
"- GP sum: a(rⁿ−1)/(r−1); functional equation f(m+n)=f(m)f(n) ⇒ f(n) = f(1)ⁿ",
"",
"---",
"*Speed habit: for every formula, know the one 'trap variant' CAT loves — e.g. average speed is NOT (u+v)/2, real return is not nominal − inflation, and strict inequalities exclude their endpoints.*"
].join("\n"),

strategy: [
"# 🧭 Strategy Playbook",
"",
"> Distilled from the last 10 years of papers (see each year's *Paper insights* tab for the specifics behind these rules).",
"",
"## The three golden rules",
"",
"1. **CAT is a selection test, not a completion test.** In every audited year, the 99th-percentile score came from answering roughly **half to two-thirds** of the paper with high accuracy — never from attempting everything.",
"2. **The −1 only applies to MCQs.** Every TITA question deserves an educated attempt; every wild MCQ guess is negative expected value unless you can eliminate two options.",
"3. **Difficulty is slot-relative and normalised.** A brutal section (2016/2017 DILR, 2023 QA) lowers the bar for everyone — don't panic-benchmark against a normal year.",
"",
"## VARC playbook (40 min, ~24 Q)",
"",
"- Passage order is yours: skim the first 3–4 lines of each RC and start with the friendliest **topic**, not the shortest passage.",
"- Answer from the text, not from the world. The classic wrong option is *true but not stated*. The second classic is *too extreme* (always/never/only).",
"- Para-jumbles: find the mandatory pair first (pronoun → antecedent, example → claim), then test only the orders containing it.",
"- Odd-sentence-out: identify the paragraph's *specific* topic; the odd one shares keywords but shifts scope.",
"- Budget: ~8 minutes per RC set, leaving ~8 for verbal ability.",
"",
"## DILR playbook (40 min, 4–5 sets)",
"",
"- **Spend the first 3–4 minutes selecting sets.** The single biggest differentiator in tough years (2016, 2017, 2023) was choosing the 2 crackable sets and committing.",
"- A set with a forced starting deduction (a fixed cell, a parity argument, totals that pin a value) is crackable; a set where you'd need to enumerate cases blindly is a trap.",
"- Do all 4–5 questions of a cracked set before moving — the marginal question in a solved set is the cheapest mark in the entire exam.",
"- Abandon rule: no concrete progress in 4 minutes → leave, flag, return only if time remains.",
"",
"## QA playbook (40 min, ~22 Q)",
"",
"- Round 1 (25 min): one pass, solve everything ≤90 seconds on sight, flag the rest. Arithmetic is ~40% of the section and mostly Round-1 material.",
"- Round 2 (15 min): return to flagged questions in order of confidence, TITA first (no penalty).",
"- Options are tools: plug endpoints, test divisibility, eliminate by magnitude before algebra.",
"- Know your 'auto-skip' topics from your stats page — a known weakness attempted under time pressure is where negatives cluster.",
"",
"## Using this site well",
"",
"1. **Practice mode** first: instant feedback per question, read every explanation including *why the wrong options tempt*.",
"2. **⏱ Timed mode** second: same questions, exam pacing (~1.8 min/question), no feedback until you submit — this is where you train selection and abandonment.",
"3. Check **📊 My stats** weekly: it shows accuracy by section and year; your two weakest cells are next week's practice plan.",
"4. Use **⭐ bookmarks** for every question you got wrong or guessed right — redo them cold after 3+ days.",
"5. Read the **Paper insights** tab before each year's set so you know what the real paper rewarded.",
"",
"---",
"*Benchmarks cited across this site are widely-reported coaching-institute estimates, not official cutoffs.*"
].join("\n")
};
